var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,k=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,ca="./this.program",da=(a,b)=>{throw b;},ea=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ea=__filename:ba&&(ea=self.location.href);var l="",fa,p;
if(k){var fs=require("node:fs");l=__dirname+"/";p=a=>{a=r(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=r(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{l=(new URL(".",ea)).href}catch{}ba&&(p=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
fa=async a=>{if(r(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ha=console.log.bind(console),w=console.error.bind(console),B,ia=!1,r=a=>a.startsWith("file://");
function C(a){f.onAbort?.(a);a=`Aborted(${a})`;w(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ja;async function ka(a){if(!B)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==ja&&B)a=new Uint8Array(B);else if(p)a=p(a);else throw"both async and sync fetching of the wasm failed";return a}async function la(a,b){try{var c=await ka(a);return await WebAssembly.instantiate(c,b)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),C(d)}}
async function ma(a){var b=ja;if(!B&&!r(b)&&!k)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return la(b,a)}class na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var oa,pa,D,qa,E,F,ra=a=>{for(;0<a.length;)a.shift()(f)},sa=[],ta=[],ua=()=>{var a=f.preRun.shift();ta.push(a)},G=0,I=null,va=!0,wa=globalThis.TextDecoder&&new TextDecoder,J=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&wa)return wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class xa{constructor(a){this.T=a-24}}
var ya=0,za=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;h++}}b[c]=0;return c-e},Aa=[],Ca=(a,b,c)=>{Aa.length=0;for(var d;d=F[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;
Aa.push(112==d?E[c>>2]:106==d?pa[c>>3]:105==d?oa[c>>2]:qa[c>>3]);c+=e?8:4}return Ba[a](...Aa)},Da={},Fa=()=>{if(!Ea){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Da)void 0===Da[b]?delete a[b]:a[b]=Da[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ea=c}return Ea},Ea,Ga=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=
d?(b+=4,++c):b+=3}return b},Ha=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ia=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ha(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ja=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+
b},Ka=()=>{if(k){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(crypto.getRandomValues(b),0)},La=a=>(La=Ka())(a),Ma=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ha(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Na=[],Oa=[];function Pa(a,b){Oa[a]={input:[],output:[],N:b};Qa(a,Ra)}
var Ra={open(a){var b=Oa[a.node.rdev];if(!b)throw new K(43);a.tty=b;a.seekable=!1},close(a){a.tty.N.fsync(a.tty)},fsync(a){a.tty.N.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.N.aa)throw new K(60);for(var e=0,h=0;h<d;h++){try{var g=a.tty.N.aa(a.tty)}catch(n){throw new K(29);}if(void 0===g&&0===e)throw new K(6);if(null===g||void 0===g)break;e++;b[c+h]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.N.Z)throw new K(60);try{for(var e=0;e<d;e++)a.tty.N.Z(a.tty,b[c+e])}catch(h){throw new K(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Sa={aa(){a:{if(!Na.length){var a=null;if(k){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Ga(a)+1);a=za(a,b,0,b.length);b.length=a;Na=b}a=Na.shift()}return a},Z(a,b){null===b||10===b?(ha(J(a.output)),a.output=
[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ha(J(a.output)),a.output=[])},Ea(){return{za:25856,Ba:5,ya:191,Aa:35387,xa:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Fa(){return 0},Ga(){return[24,80]}},Ta={Z(a,b){null===b||10===b?(w(J(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(w(J(a.output)),a.output=[])}},L={I:null,K(){return L.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);
L.I||(L.I={dir:{node:{L:L.B.L,J:L.B.J,lookup:L.B.lookup,R:L.B.R,rename:L.B.rename,unlink:L.B.unlink,rmdir:L.B.rmdir,readdir:L.B.readdir,symlink:L.B.symlink},stream:{H:L.C.H}},file:{node:{L:L.B.L,J:L.B.J},stream:{H:L.C.H,read:L.C.read,write:L.C.write,ga:L.C.ga,ia:L.C.ia}},link:{node:{L:L.B.L,J:L.B.J,readlink:L.B.readlink},stream:{}},$:{node:{L:L.B.L,J:L.B.J},stream:Ua}});c=Va(a,b,c,d);16384===(c.mode&61440)?(c.B=L.I.dir.node,c.C=L.I.dir.stream,c.D={}):32768===(c.mode&61440)?(c.B=L.I.file.node,c.C=
L.I.file.stream,c.G=0,c.D=L.ka??(L.ka=new Uint8Array(0))):40960===(c.mode&61440)?(c.B=L.I.link.node,c.C=L.I.link.stream):8192===(c.mode&61440)&&(c.B=L.I.$.node,c.C=L.I.$.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.D[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},B:{L(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.G:40960===(a.mode&61440)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},J(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.G!=b&&(c=a.D,a.D=new Uint8Array(b),a.D.set(c.subarray(0,Math.min(b,a.G))),a.G=b))},lookup(){L.V||(L.V=new K(44),L.V.stack="<generic error, no stack>");throw L.V;},R(a,b,c,d){return L.createNode(a,b,c,d)},rename(a,b,c){try{var d=M(b,c)}catch(h){}if(d){if(16384===
(a.mode&61440))for(var e in d.D)throw new K(55);e=Wa(d.parent.id,d.name);if(N[e]===d)N[e]=d.M;else for(e=N[e];e;){if(e.M===d){e.M=d.M;break}e=e.M}}delete a.parent.D[a.name];b.D[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.D[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=M(a,b),d;for(d in c.D)throw new K(55);delete a.D[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.D)]},symlink(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;
return a},readlink(a){if(40960!==(a.mode&61440))throw new K(28);return a.link}},C:{read(a,b,c,d,e){if(e>=a.node.G)return 0;d=Math.min(a.node.G-e,d);b.set(a.node.D.subarray(e,e+d),c);return d},write(a,b,c,d,e,h){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(h)a.D=b.subarray(c,c+d),a.G=d;else if(0===a.G&&0===e)a.D=b.slice(c,c+d),a.G=d;else{h=e+d;var g=a.D.length;g>=h||(h=Math.max(h,g*(1048576>g?2:1.125)>>>0),g&&(h=Math.max(h,256)),g=a.D.subarray(0,a.G),a.D=new Uint8Array(h),a.D.set(g));a.D.set(b.subarray(c,
c+d),e);a.G=Math.max(a.G,e+d)}return d},H(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.G);if(0>b)throw new K(28);return b},ga(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new K(43);a=a.node.D;if(e&2||a.buffer!==D.buffer){d=!0;C();e=void 0;if(!e)throw new K(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);D.set(a,e)}}else d=!1,e=a.byteOffset;return{T:e,wa:d}},ia(a,b,c,d){L.C.write(a,b,0,d,c,!1);return 0}}},Xa=(a,b)=>
{var c=0;a&&(c|=365);b&&(c|=146);return c},Ya=null,Za={},O=[],$a=1,N=null,ab=!1,bb=!0,K=class{name="ErrnoError";constructor(a){this.O=a}},cb=class{P={};node=null;get flags(){return this.P.flags}set flags(a){this.P.flags=a}get position(){return this.P.position}set position(a){this.P.position=a}},db=class{B={};C={};S=null;constructor(a,b,c,d){a||=this;this.parent=a;this.K=a.K;this.id=$a++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&
365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function P(a,b={}){if(!a)throw new K(44);b.X??(b.X=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=Ya,e="/",h=0;h<a.length;h++){var g=h===a.length-1;if(g&&b.parent)break;if("."!==a[h])if(".."===a[h])if(e=Ja(e),d===d.parent){a=e+"/"+a.slice(h+1).join("/");c--;continue a}else d=d.parent;else{e=Ia(e+"/"+a[h]);try{d=M(d,a[h])}catch(n){if(44===n?.O&&g&&b.ta)return{path:e};throw n;}!d.S||g&&!b.X||(d=d.S.root);if(40960===(d.mode&61440)&&(!g||b.W)){if(!d.B.readlink)throw new K(52);
d=d.B.readlink(d);"/"===d.charAt(0)||(d=Ja(e)+"/"+d);a=d+"/"+a.slice(h+1).join("/");continue a}}}return{path:e,node:d}}throw new K(32);}function Wa(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%N.length}function M(a,b){var c=16384===(a.mode&61440)?(c=R(a,"x"))?c:a.B.lookup?0:2:54;if(c)throw new K(c);for(c=N[Wa(a.id,b)];c;c=c.M){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.B.lookup(a,b)}
function Va(a,b,c,d){a=new db(a,b,c,d);b=Wa(a.parent.id,a.name);a.M=N[b];return N[b]=a}function R(a,b){return bb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function eb(a,b){if(16384!==(a.mode&61440))return 54;try{return M(a,b),20}catch(c){}return R(a,"wx")}function S(a){a=O[a];if(!a)throw new K(8);return a}
function fb(a,b){var c=null?.C.J,d=c?null:a;c??=a.B.J;if(!c)throw new K(63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new K(22);throw e;}}var Ua={open(a){a.C=Za[a.node.rdev].C;a.C.open?.(a)},H(){throw new K(70);}};function Qa(a,b){Za[a]={C:b}}
function gb(a,b){var c="/"===b;if(c&&Ya)throw new K(10);if(!c&&b){var d=P(b,{X:!1});b=d.path;d=d.node;if(d.S)throw new K(10);if(16384!==(d.mode&61440))throw new K(54);}b={type:a,Ka:{},ha:b,sa:[]};a=a.K(b);a.K=b;b.root=a;c?Ya=a:d&&(d.S=b,d.K&&d.K.sa.push(b))}function hb(a,b,c){var d=P(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new K(28);if("."===a||".."===a)throw new K(20);var e=eb(d,a);if(e)throw new K(e);if(!d.B.R)throw new K(63);return d.B.R(d,a,b,c)}
function T(a){return hb(a,16895,0)}function U(a,b,c){"undefined"==typeof c&&(c=b,b=438);hb(a,b|8192,c)}function ib(a,b){if(!Ma(a))throw new K(44);var c=P(b,{parent:!0}).node;if(!c)throw new K(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=eb(c,b);if(d)throw new K(d);if(!c.B.symlink)throw new K(63);c.B.symlink(c,b,a)}
function jb(a,b){if(""===a)throw new K(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");var h=P(a,{W:!(b&131072),ta:!0});d=h.node;a=h.path}h=!1;if(b&64)if(d){if(b&128)throw new K(20);}else{if(e)throw new K(31);d=hb(a,c|511,0);h=!0}if(!d)throw new K(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new K(54);
if(!h&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=16384===(d.mode&61440)&&("r"!==e||b&576)?31:R(d,e)):e=44,e))throw new K(e);if(b&512&&!h){e=d;e="string"==typeof e?P(e,{W:!0}).node:e;if(16384===(e.mode&61440))throw new K(31);if(32768!==(e.mode&61440))throw new K(28);if(a=R(e,"w"))throw new K(a);fb(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.K.ha;var g=g?"/"!==e[e.length-1]?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:e.name;e=e.parent}b={node:d,
path:g,flags:b&-131713,seekable:!0,position:0,C:d.C,va:[],error:!1};g=-1;b=Object.assign(new cb,b);if(-1==g)a:{for(g=0;4096>=g;g++)if(!O[g])break a;throw new K(33);}b.fd=g;O[g]=b;b.C.open&&b.C.open(b);h&&(c&=511,d="string"==typeof d?P(d,{W:!0}).node:d,fb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Da:void 0}))}function kb(a,b,c){if(null===a.fd)throw new K(8);if(!a.seekable||!a.C.H)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.C.H(a,b,c);a.va=[]}
function V(a,b,c){a=Ia("/dev/"+a);var d=Xa(!!b,!!c);V.ea??(V.ea=64);var e=V.ea++<<8|0;Qa(e,{open(h){h.seekable=!1},close(){c?.buffer?.length&&c(10)},read(h,g,n,t){for(var m=0,z=0;z<t;z++){try{var q=b()}catch(v){throw new K(29);}if(void 0===q&&0===m)throw new K(6);if(null===q||void 0===q)break;m++;g[n+z]=q}m&&(h.node.atime=Date.now());return m},write(h,g,n,t){for(var m=0;m<t;m++)try{c(g[n+m])}catch(z){throw new K(29);}t&&(h.node.mtime=h.node.ctime=Date.now());return m}});U(a,d,e)}
var W={},X=a=>{var b=Ga(a)+1,c=lb(b);c&&za(a,F,c,b);return c};N=Array(4096);gb(L,"/");T("/tmp");T("/home");T("/home/web_user");(function(){T("/dev");Qa(259,{read:()=>0,write:(d,e,h,g)=>g,H:()=>0});U("/dev/null",259);Pa(1280,Sa);Pa(1536,Ta);U("/dev/tty",1280);U("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(La(a),b=a.byteLength);return a[--b]};V("random",c);V("urandom",c);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");gb({K(){var b=Va(a,"fd",16895,73);b.C={H:L.C.H};b.B={lookup(c,d){c=+d;var e=S(c);c={parent:null,K:{ha:"fake"},B:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(O.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();f.noExitRuntime&&(va=f.noExitRuntime);f.print&&(ha=f.print);f.printErr&&(w=f.printErr);f.wasmBinary&&(B=f.wasmBinary);f.thisProgram&&(ca=f.thisProgram);
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();f.stringToNewUTF8=X;
var Ba={236548:a=>{f.A[a].save()},236576:a=>{f.A[a].restore()},236607:()=>{let a;a=0<f.U.length?f.U.pop():f.A.length;0===a?f.A[a]=document.getElementById("canvas").getContext("2d"):f.A[a]=(new OffscreenCanvas(1,1)).getContext("2d");return a},236918:a=>{if(0==a)throw Error("Tried to delete the main context");f.A[a]=null;f.U.push(a)},237043:(a,b,c)=>{f.A[a].canvas.width=b;f.A[a].canvas.height=c},237118:(a,b,c,d,e)=>{f.A[a].fillStyle="rgba("+d+","+c+","+b+","+e/255+")"},237191:(a,b,c,d,e)=>{f.A[a].strokeStyle=
"rgba("+d+","+c+","+b+","+e/255+")"},237266:(a,b)=>{f.A[a].lineWidth=b},237302:(a,b)=>{f.A[a].font=b+"px Ubuntu"},237347:(a,b)=>{f.A[a].globalAlpha=b},237385:a=>{f.A[a].lineCap="round"},237424:a=>{f.A[a].lineJoin="round"},237464:a=>{f.A[a].textAlign="center"},237506:a=>{f.A[a].textBaseline="middle"},237551:a=>{f.A[a].beginPath()},237584:(a,b,c)=>{f.A[a].moveTo(b,c)},237620:(a,b,c)=>{f.A[a].lineTo(b,c)},237656:(a,b,c,d,e)=>{f.A[a].quadraticCurveTo(b,c,d,e)},237710:(a,b,c,d,e,h,g)=>{f.A[a].bezierCurveTo(b,
c,d,e,h,g)},237769:(a,b,c,d,e,h,g)=>{f.A[a].arc(b,c,d,e,h,!!g)},237820:(a,b,c,d,e,h)=>{f.A[a].ellipse(b,c,d,e,h,2*Math.PI,0)},237885:(a,b,c,d,e)=>{f.A[a].fillRect(b,c,d,e)},237931:(a,b,c,d,e)=>{f.A[a].strokeRect(b,c,d,e)},237979:(a,b,c,d,e)=>{f.A[a].rect(b,c,d,e)},238021:a=>{f.A[a].closePath()},238054:(a,b)=>{f.A[a].fill(b?"nonzero":"evenodd")},238108:a=>{f.A[a].stroke()},238138:a=>{f.A[a].clip()},238166:(a,b,c,d)=>{f.A[a].drawImage(f.A[b].canvas,c,d)},238229:(a,b,c,d,e,h)=>{a=f.A[a];const g=f.ba;
if(g&&g.complete&&0!==g.naturalWidth){d=Math.max(1,Math.round(d));if(!f.da||f.ma!==d){const n=document.createElement("canvas");n.width=n.height=d;const t=n.getContext("2d");t.imageSmoothingEnabled=!0;t.drawImage(g,0,0,d,d);f.da=a.createPattern(n,"repeat");f.ma=d}a.save();a.fillStyle=f.da;a.translate(b,c);a.fillRect(-b,-c,e,h);a.restore()}else a.fillStyle="#1ea761",a.fillRect(0,0,e,h)},238891:(a,b,c)=>{f.A[a].fillText(f.TextDecoder.decode(F.subarray(b,b+c)),0,0)},238980:(a,b,c)=>{f.A[a].strokeText(f.TextDecoder.decode(F.subarray(b,
b+c)),0,0)},239071:(a,b,c)=>f.A[a].measureText(f.TextDecoder.decode(F.subarray(b,b+c)),0,0).width,239176:(a,b,c,d,e,h,g)=>{f.A[a].setTransform(b,c,e,h,d,g)},239234:()=>{f.fa=!1;fetch("map-data.json").then(function(a){return a.json()}).then(function(a){const b={};for(var c in a.ua)b[c]=a.ua[c].map(function(e){return{path:new Path2D(e.d),fill:e.fill,stroke:e.stroke,ja:e.ja}});c=a.Ha.length;const d=[];for(let e=0;e<c;e++)d.push(new Map);for(const e of a.La)d[e.l].set(50*e.r+e.c,e);f.ra=b;f.oa=d;f.pa=
a.Ja;f.Ia=c;f.na=a.Ca;f.qa=a.Ma;f.fa=!0})},239897:(a,b,c,d,e)=>{function h(q,v){g.save();const A=0!==(v&2147483648),x=0!==(v&1073741824);0!==(v&536870912)&&g.transform(0,1,1,0,0,0);A&&g.transform(-1,0,0,1,n,0);x&&g.transform(1,0,0,-1,0,n);for(const u of q)u.fill&&(g.fillStyle=u.fill,g.fill(u.path)),u.stroke&&(g.strokeStyle=u.stroke,g.lineWidth=u.ja,g.lineJoin="round",g.stroke(u.path));g.restore()}if(f.fa){var g=f.A[a];a=f.na;var n=f.qa,t=a/n,m=f.ra,z=f.oa;for(let q=0;q<z.length;q++){const v=z[q];
for(let A=d;A<e;A++)for(let x=b;x<c;x++){const u=v.get(50*A+x);if(!u)continue;const y=m[u.gid];y&&(g.save(),g.translate(x*a,A*a),g.scale(t,t),h(y,u.la),g.restore())}}for(const q of f.pa)!(t=m[q.gid])||q.x+q.w<b*a||q.x>c*a||q.y+q.h<d*a||q.y>e*a||(g.save(),g.translate(q.x,q.y),g.scale(q.w/n,q.h/n),h(t,q.la),g.restore())}},241318:a=>(a=window.localStorage[a?J(F,a):""])?X(a):0,241416:a=>{delete window.localStorage[a?J(F,a):""]},241466:(a,b)=>{window.localStorage[a?J(F,a):""]=b?J(F,b):""},241528:()=>performance.now(),
241558:(a,b,c,d)=>{const e=a?J(F,a):"";a=document.createElement("input");a.id=e;a.type=c?"password":"text";a.style.position="absolute";a.style["font-family"]="Ubuntu";a.style.display="none";a.style["border-width"]="0px";a.style.background="transparent";a.style.border="none";a.style.outline="none";a.style["padding-left"]="5px";a.maxLength=b.toString();a.setAttribute("spellcheck","false");if(b=d?J(F,d):"")a.placeholder=b;document.body.appendChild(a)},242131:a=>{a=a?J(F,a):"";document.getElementById(a).style.display=
"block"},242240:a=>{a=a?J(F,a):"";document.getElementById(a).style.display="none"},242348:(a,b,c,d,e,h)=>{a=a?J(F,a):"";a=document.getElementById(a);const g=devicePixelRatio*(f.F||1);a.style.left=(b-d/2)/g+"px";a.style.top=(c-e/2)/g+"px";a.style.width=d/g-10+"px";a.style.height=e/g+"px";a.style["font-size"]=e/g*.66*h+"px"},242705:a=>{a=a?J(F,a):"";a=document.getElementById(a);return X(a.value)},242820:(a,b,c)=>{a=a?J(F,a):"";document.getElementById(a).value=(b?J(F,b):"").slice(0,c)},242942:a=>{try{window.open(a?
J(F,a):"")}catch(b){}},242997:()=>{window.addEventListener("keydown",a=>{!a.repeat&&mb(X(a.code),0)});window.addEventListener("keyup",a=>{!a.repeat&&mb(X(a.code),1)});window.addEventListener("mousedown",a=>{Y(a.clientX*devicePixelRatio*(f.F||1),a.clientY*devicePixelRatio*(f.F||1),0,+!!a.button)});window.addEventListener("mousemove",a=>{Y(a.clientX*devicePixelRatio*(f.F||1),a.clientY*devicePixelRatio*(f.F||1),1,+!!a.button)});window.addEventListener("mouseup",a=>{Y(a.clientX*devicePixelRatio*(f.F||
1),a.clientY*devicePixelRatio*(f.F||1),2,+!!a.button)});window.addEventListener("touchstart",a=>{for(const b of a.changedTouches)Z(b.clientX*devicePixelRatio*(f.F||1),b.clientY*devicePixelRatio*(f.F||1),0,b.identifier)},{passive:!1});window.addEventListener("touchmove",a=>{for(const b of a.changedTouches)Z(b.clientX*devicePixelRatio*(f.F||1),b.clientY*devicePixelRatio*(f.F||1),1,b.identifier)},{passive:!1});window.addEventListener("touchend",a=>{for(const b of a.changedTouches)Z(b.clientX*devicePixelRatio*
(f.F||1),b.clientY*devicePixelRatio*(f.F||1),2,b.identifier)},{passive:!1});window.addEventListener("touchcancel",a=>{for(const b of a.changedTouches)Z(b.clientX*devicePixelRatio*(f.F||1),b.clientY*devicePixelRatio*(f.F||1),2,b.identifier)},{passive:!1});window.addEventListener("paste",a=>{try{const b=a.clipboardData.getData("text/plain");nb(X(b))}catch(b){}},{capture:!0});window.addEventListener("wheel",a=>{ob(a.deltaY)})},245015:()=>{function a(h){var g=pb();g!==c&&(c=g,e.style.display="flex",d=
h+450);if(h-b>=(g?0:1E3/30-1)){b=h;f.F=g?1:.5;var n=devicePixelRatio*f.F;g=Math.max(1,Math.floor(innerWidth*n));n=Math.max(1,Math.floor(innerHeight*n));f.canvas.width=g;f.canvas.height=n;qb(h,g,n)}d&&h>=d&&(e.style.display="none",d=0);requestAnimationFrame(a)}let b=-1E9,c=pb(),d=0;const e=document.createElement("div");e.style.cssText="position:absolute;inset:0;background:#000;color:#fff;font:bold 48pt sans-serif;display:none;align-items:center;justify-content:center;z-index:10;";e.textContent="Loading";
document.body.appendChild(e);requestAnimationFrame(a)},246059:()=>{f.canvas=document.getElementById("canvas");f.canvas.width=innerWidth*devicePixelRatio;f.canvas.height=innerHeight*devicePixelRatio;f.canvas.oncontextmenu=function(){return!1};window.onbeforeunload=function(){return"Are you sure?"};f.A=[];f.U=[];f.TextDecoder=new TextDecoder("utf8");f.ba=new Image;f.ba.src="grass_bg.svg"},246511:()=>/iPhone|iPad|iPod|Android|BlackBerry/i.test(navigator.userAgent),246588:a=>{function b(){let d=f.socket=
new WebSocket(c);d.binaryType="arraybuffer";d.onopen=function(){rb(0,0,0)};d.onclose=function(e){rb(2,e.code,X(e.reason));setTimeout(b,1E3)};d.onmessage=function(e){F.set(new Uint8Array(e.data),a);rb(1,e.data.byteLength,0)}}let c=("https:"===location.protocol?"wss://":"ws://")+location.host;setTimeout(b,1E3)},247105:(a,b)=>{1==f.socket?.readyState&&f.socket.send(F.subarray(a,a+b))},247197:(a,b,c,d)=>{window.localStorage[f.TextDecoder.decode(F.subarray(a,a+b))]=f.TextDecoder.decode(F.subarray(c,c+
d))},247331:(a,b,c,d)=>{a=window.localStorage[f.TextDecoder.decode(F.subarray(a,a+b))];if(!a)return 0;a=a.slice(0,d);F.set((new TextEncoder).encode(a),c);return a.length}},sb,pb,Y,mb,Z,ob,nb,qb,rb,lb,tb,ub={b:(a,b,c,d)=>C(`Assertion failed: ${a?J(F,a):""}, at: `+[b?b?J(F,b):"":"unknown filename",c,d?d?J(F,d):"":"unknown function"]),c:(a,b,c)=>{a=new xa(a);E[a.T+16>>2]=0;E[a.T+4>>2]=b;E[a.T+8>>2]=c;ya++;C()},i:()=>C(""),e:(a,b,c)=>Ca(a,b,c),a:(a,b,c)=>Ca(a,b,c),d:(a,b,c)=>Ca(a,b,c),j:()=>Date.now(),
h:()=>{C("OOM")},k:(a,b)=>{var c=0,d=0,e;for(e of Fa()){var h=b+c;E[a+d>>2]=h;c+=za(e,F,h,Infinity)+1;d+=4}return 0},l:(a,b)=>{var c=Fa();E[a>>2]=c.length;a=0;for(var d of c)a+=Ga(d)+1;E[b>>2]=a;return 0},m:function(a){try{var b=S(a);if(null===b.fd)throw new K(8);b.Y&&(b.Y=null);try{b.C.close&&b.C.close(b)}catch(c){throw c;}finally{O[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof W||"ErrnoError"!==c.name)throw c;return c.O}},n:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var h,g=b=0;g<
c;g++){var n=E[a>>2],t=E[a+4>>2];a+=8;var m=e,z=n,q=t,v=h,A=D;if(0>q||0>v)throw new K(28);if(null===m.fd)throw new K(8);if(1===(m.flags&2097155))throw new K(8);if(16384===(m.node.mode&61440))throw new K(31);if(!m.C.read)throw new K(28);var x="undefined"!=typeof v;if(!x)v=m.position;else if(!m.seekable)throw new K(70);var u=m.C.read(m,A,z,q,v);x||(m.position+=u);var y=u;if(0>y){var Q=-1;break a}b+=y;if(y<t)break;"undefined"!=typeof h&&(h+=y)}Q=b}E[d>>2]=Q;return 0}catch(H){if("undefined"==typeof W||
"ErrnoError"!==H.name)throw H;return H.O}},g:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);kb(e,b,c);pa[d>>3]=BigInt(e.position);e.Y&&0===b&&0===c&&(e.Y=null);return 0}catch(h){if("undefined"==typeof W||"ErrnoError"!==h.name)throw h;return h.O}},f:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var h,g=b=0;g<c;g++){var n=E[a>>2],t=E[a+4>>2];a+=8;var m=e,z=n,q=t,v=h,A=D;if(0>q||0>v)throw new K(28);if(null===m.fd)throw new K(8);if(0===(m.flags&
2097155))throw new K(8);if(16384===(m.node.mode&61440))throw new K(31);if(!m.C.write)throw new K(28);m.seekable&&m.flags&1024&&kb(m,0,2);var x="undefined"!=typeof v;if(!x)v=m.position;else if(!m.seekable)throw new K(70);var u=m.C.write(m,A,z,q,v,void 0);x||(m.position+=u);var y=u;if(0>y){var Q=-1;break a}b+=y;if(y<t)break;"undefined"!=typeof h&&(h+=y)}Q=b}E[d>>2]=Q;return 0}catch(H){if("undefined"==typeof W||"ErrnoError"!==H.name)throw H;return H.O}}};
function vb(){function a(){f.calledRun=!0;if(!ia){if(!f.noFSInit&&!ab){var b,c;ab=!0;b??=f.stdin;c??=f.stdout;d??=f.stderr;b?V("stdin",b):ib("/dev/tty","/dev/stdin");c?V("stdout",null,c):ib("/dev/tty","/dev/stdout");d?V("stderr",null,d):ib("/dev/tty1","/dev/stderr");jb("/dev/stdin",0);jb("/dev/stdout",1);jb("/dev/stderr",1)}wb.p();bb=!1;f.onRuntimeInitialized?.();if(!f.noInitialRun){var d=sb;try{var e=d(0,0);va||(f.onExit?.(e),ia=!0);da(e,new na(e))}catch(h){h instanceof na||"unwind"==h||da(1,h)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)e=f.postRun.shift(),sa.push(e);ra(sa)}}if(0<G)I=vb;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ua();ra(ta);0<G?I=vb:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}var wb;
(async function(){function a(c){c=wb=c.exports;sb=f._main=c.q;pb=f._get_high_quality=c.r;Y=f._mouse_event=c.s;mb=f._key_event=c.t;Z=f._touch_event=c.u;ob=f._wheel_event=c.v;nb=f._clipboard_event=c.w;qb=f._loop=c.x;rb=f._on_message=c.y;lb=c.z;tb=c.o;c=tb.buffer;D=new Int8Array(c);new Int16Array(c);F=new Uint8Array(c);new Uint16Array(c);oa=new Int32Array(c);E=new Uint32Array(c);new Float32Array(c);qa=new Float64Array(c);pa=new BigInt64Array(c);new BigUint64Array(c);G--;f.monitorRunDependencies?.(G);
0==G&&I&&(c=I,I=null,c());return wb}G++;f.monitorRunDependencies?.(G);var b={a:ub};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ja??=f.locateFile?f.locateFile("floir-client.wasm",l):l+"floir-client.wasm";return a((await ma(b)).instance)})();vb();
