var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,k=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,ca="./this.program",da=(a,b)=>{throw b;},ea=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ea=__filename:ba&&(ea=self.location.href);var l="",fa,n;
if(k){var fs=require("node:fs");l=__dirname+"/";n=a=>{a=p(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=p(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{l=(new URL(".",ea)).href}catch{}ba&&(n=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
fa=async a=>{if(p(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ha=console.log.bind(console),q=console.error.bind(console),w,ia=!1,p=a=>a.startsWith("file://");
function y(a){f.onAbort?.(a);a=`Aborted(${a})`;q(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ja;async function ka(a){if(!w)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==ja&&w)a=new Uint8Array(w);else if(n)a=n(a);else throw"both async and sync fetching of the wasm failed";return a}async function la(a,b){try{var c=await ka(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),y(d)}}
async function ma(a){var b=ja;if(!w&&!p(b)&&!k)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return la(b,a)}class na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var oa,pa,z,qa,B,C,ra=a=>{for(;0<a.length;)a.shift()(f)},sa=[],ta=[],ua=()=>{var a=f.preRun.shift();ta.push(a)},D=0,F=null,va=!0,wa=globalThis.TextDecoder&&new TextDecoder,G=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&wa)return wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class xa{constructor(a){this.S=a-24}}
var za=0,Aa=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;g++}}b[c]=0;return c-e},Ba=[],Da=(a,b,c)=>{Ba.length=0;for(var d;d=C[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;
Ba.push(112==d?B[c>>2]:106==d?pa[c>>3]:105==d?oa[c>>2]:qa[c>>3]);c+=e?8:4}return Ca[a](...Ba)},Ea={},Ga=()=>{if(!Fa){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Ea)void 0===Ea[b]?delete a[b]:a[b]=Ea[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Fa=c}return Fa},Fa,Ha=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=
d?(b+=4,++c):b+=3}return b},Ia=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ja=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ia(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ka=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+
b},La=()=>{if(k){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(crypto.getRandomValues(b),0)},Ma=a=>(Ma=La())(a),Na=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ia(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Oa=[],Pa=[];function Qa(a,b){Pa[a]={input:[],output:[],M:b};Ra(a,Sa)}
var Sa={open(a){var b=Pa[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close(a){a.tty.M.fsync(a.tty)},fsync(a){a.tty.M.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.M.$)throw new H(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.M.$(a.tty)}catch(r){throw new H(29);}if(void 0===h&&0===e)throw new H(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.M.Y)throw new H(60);try{for(var e=0;e<d;e++)a.tty.M.Y(a.tty,b[c+e])}catch(g){throw new H(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Ta={$(){a:{if(!Oa.length){var a=null;if(k){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Ha(a)+1);a=Aa(a,b,0,b.length);b.length=a;Oa=b}a=Oa.shift()}return a},Y(a,b){null===b||10===b?(ha(G(a.output)),a.output=
[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ha(G(a.output)),a.output=[])},qa(){return{ma:25856,oa:5,la:191,na:35387,ka:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ra(){return 0},sa(){return[24,80]}},Ua={Y(a,b){null===b||10===b?(q(G(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(q(G(a.output)),a.output=[])}},I={H:null,J(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);
I.H||(I.H={dir:{node:{K:I.B.K,I:I.B.I,lookup:I.B.lookup,P:I.B.P,rename:I.B.rename,unlink:I.B.unlink,rmdir:I.B.rmdir,readdir:I.B.readdir,symlink:I.B.symlink},stream:{G:I.C.G}},file:{node:{K:I.B.K,I:I.B.I},stream:{G:I.C.G,read:I.C.read,write:I.C.write,ba:I.C.ba,ea:I.C.ea}},link:{node:{K:I.B.K,I:I.B.I,readlink:I.B.readlink},stream:{}},Z:{node:{K:I.B.K,I:I.B.I},stream:Va}});c=Wa(a,b,c,d);16384===(c.mode&61440)?(c.B=I.H.dir.node,c.C=I.H.dir.stream,c.D={}):32768===(c.mode&61440)?(c.B=I.H.file.node,c.C=
I.H.file.stream,c.F=0,c.D=I.fa??(I.fa=new Uint8Array(0))):40960===(c.mode&61440)?(c.B=I.H.link.node,c.C=I.H.link.stream):8192===(c.mode&61440)&&(c.B=I.H.Z.node,c.C=I.H.Z.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.D[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},B:{K(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.F:40960===(a.mode&61440)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},I(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.F!=b&&(c=a.D,a.D=new Uint8Array(b),a.D.set(c.subarray(0,Math.min(b,a.F))),a.F=b))},lookup(){I.U||(I.U=new H(44),I.U.stack="<generic error, no stack>");throw I.U;},P(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){try{var d=J(b,c)}catch(g){}if(d){if(16384===
(a.mode&61440))for(var e in d.D)throw new H(55);e=Xa(d.parent.id,d.name);if(K[e]===d)K[e]=d.L;else for(e=K[e];e;){if(e.L===d){e.L=d.L;break}e=e.L}}delete a.parent.D[a.name];b.D[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.D[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=J(a,b),d;for(d in c.D)throw new H(55);delete a.D[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.D)]},symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;
return a},readlink(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},C:{read(a,b,c,d,e){if(e>=a.node.F)return 0;d=Math.min(a.node.F-e,d);b.set(a.node.D.subarray(e,e+d),c);return d},write(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(g)a.D=b.subarray(c,c+d),a.F=d;else if(0===a.F&&0===e)a.D=b.slice(c,c+d),a.F=d;else{g=e+d;var h=a.D.length;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),h&&(g=Math.max(g,256)),h=a.D.subarray(0,a.F),a.D=new Uint8Array(g),a.D.set(h));a.D.set(b.subarray(c,
c+d),e);a.F=Math.max(a.F,e+d)}return d},G(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.F);if(0>b)throw new H(28);return b},ba(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.D;if(e&2||a.buffer!==z.buffer){d=!0;y();e=void 0;if(!e)throw new H(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);z.set(a,e)}}else d=!1,e=a.byteOffset;return{S:e,ja:d}},ea(a,b,c,d){I.C.write(a,b,0,d,c,!1);return 0}}},Ya=(a,b)=>
{var c=0;a&&(c|=365);b&&(c|=146);return c},Za=null,$a={},L=[],ab=1,K=null,bb=!1,cb=!0,H=class{name="ErrnoError";constructor(a){this.N=a}},db=class{O={};node=null;get flags(){return this.O.flags}set flags(a){this.O.flags=a}get position(){return this.O.position}set position(a){this.O.position=a}},eb=class{B={};C={};R=null;constructor(a,b,c,d){a||=this;this.parent=a;this.J=a.J;this.id=ab++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&
365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function M(a,b={}){if(!a)throw new H(44);b.W??(b.W=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(r=>!!r);for(var d=Za,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Ka(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=Ja(e+"/"+a[g]);try{d=J(d,a[g])}catch(r){if(44===r?.N&&h&&b.ha)return{path:e};throw r;}!d.R||h&&!b.W||(d=d.R.root);if(40960===(d.mode&61440)&&(!h||b.V)){if(!d.B.readlink)throw new H(52);
d=d.B.readlink(d);"/"===d.charAt(0)||(d=Ka(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new H(32);}function Xa(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%K.length}function J(a,b){var c=16384===(a.mode&61440)?(c=Q(a,"x"))?c:a.B.lookup?0:2:54;if(c)throw new H(c);for(c=K[Xa(a.id,b)];c;c=c.L){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.B.lookup(a,b)}
function Wa(a,b,c,d){a=new eb(a,b,c,d);b=Xa(a.parent.id,a.name);a.L=K[b];return K[b]=a}function Q(a,b){return cb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function fb(a,b){if(16384!==(a.mode&61440))return 54;try{return J(a,b),20}catch(c){}return Q(a,"wx")}function R(a){a=L[a];if(!a)throw new H(8);return a}
function gb(a,b){var c=null?.C.I,d=c?null:a;c??=a.B.I;if(!c)throw new H(63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new H(22);throw e;}}var Va={open(a){a.C=$a[a.node.rdev].C;a.C.open?.(a)},G(){throw new H(70);}};function Ra(a,b){$a[a]={C:b}}
function hb(a,b){var c="/"===b;if(c&&Za)throw new H(10);if(!c&&b){var d=M(b,{W:!1});b=d.path;d=d.node;if(d.R)throw new H(10);if(16384!==(d.mode&61440))throw new H(54);}b={type:a,ua:{},da:b,ga:[]};a=a.J(b);a.J=b;b.root=a;c?Za=a:d&&(d.R=b,d.J&&d.J.ga.push(b))}function ib(a,b,c){var d=M(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new H(28);if("."===a||".."===a)throw new H(20);var e=fb(d,a);if(e)throw new H(e);if(!d.B.P)throw new H(63);return d.B.P(d,a,b,c)}
function S(a){return ib(a,16895,0)}function T(a,b,c){"undefined"==typeof c&&(c=b,b=438);ib(a,b|8192,c)}function jb(a,b){if(!Na(a))throw new H(44);var c=M(b,{parent:!0}).node;if(!c)throw new H(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=fb(c,b);if(d)throw new H(d);if(!c.B.symlink)throw new H(63);c.B.symlink(c,b,a)}
function kb(a,b){if(""===a)throw new H(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");var g=M(a,{V:!(b&131072),ha:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new H(20);}else{if(e)throw new H(31);d=ib(a,c|511,0);g=!0}if(!d)throw new H(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new H(54);
if(!g&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=16384===(d.mode&61440)&&("r"!==e||b&576)?31:Q(d,e)):e=44,e))throw new H(e);if(b&512&&!g){e=d;e="string"==typeof e?M(e,{V:!0}).node:e;if(16384===(e.mode&61440))throw new H(31);if(32768!==(e.mode&61440))throw new H(28);if(a=Q(e,"w"))throw new H(a);gb(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.J.da;var h=h?"/"!==e[e.length-1]?`${e}/${h}`:e+h:e;break a}h=h?`${e.name}/${h}`:e.name;e=e.parent}b={node:d,
path:h,flags:b&-131713,seekable:!0,position:0,C:d.C,ia:[],error:!1};h=-1;b=Object.assign(new db,b);if(-1==h)a:{for(h=0;4096>=h;h++)if(!L[h])break a;throw new H(33);}b.fd=h;L[h]=b;b.C.open&&b.C.open(b);g&&(c&=511,d="string"==typeof d?M(d,{V:!0}).node:d,gb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),pa:void 0}))}function lb(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.C.G)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.C.G(a,b,c);a.ia=[]}
function U(a,b,c){a=Ja("/dev/"+a);var d=Ya(!!b,!!c);U.aa??(U.aa=64);var e=U.aa++<<8|0;Ra(e,{open(g){g.seekable=!1},close(){c?.buffer?.length&&c(10)},read(g,h,r,t){for(var m=0,A=0;A<t;A++){try{var u=b()}catch(v){throw new H(29);}if(void 0===u&&0===m)throw new H(6);if(null===u||void 0===u)break;m++;h[r+A]=u}m&&(g.node.atime=Date.now());return m},write(g,h,r,t){for(var m=0;m<t;m++)try{c(h[r+m])}catch(A){throw new H(29);}t&&(g.node.mtime=g.node.ctime=Date.now());return m}});T(a,d,e)}
var V={},W=a=>{var b=Ha(a)+1,c=mb(b);c&&Aa(a,C,c,b);return c};K=Array(4096);hb(I,"/");S("/tmp");S("/home");S("/home/web_user");(function(){S("/dev");Ra(259,{read:()=>0,write:(d,e,g,h)=>h,G:()=>0});T("/dev/null",259);Qa(1280,Ta);Qa(1536,Ua);T("/dev/tty",1280);T("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ma(a),b=a.byteLength);return a[--b]};U("random",c);U("urandom",c);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");hb({J(){var b=Wa(a,"fd",16895,73);b.C={G:I.C.G};b.B={lookup(c,d){c=+d;var e=R(c);c={parent:null,J:{da:"fake"},B:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(L.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();f.noExitRuntime&&(va=f.noExitRuntime);f.print&&(ha=f.print);f.printErr&&(q=f.printErr);f.wasmBinary&&(w=f.wasmBinary);f.thisProgram&&(ca=f.thisProgram);
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();f.stringToNewUTF8=W;
var Ca={183204:a=>{f.A[a].save()},183232:a=>{f.A[a].restore()},183263:()=>{let a;a=0<f.T.length?f.T.pop():f.A.length;0===a?f.A[a]=document.getElementById("canvas").getContext("2d"):f.A[a]=(new OffscreenCanvas(1,1)).getContext("2d");return a},183574:a=>{if(0==a)throw Error("Tried to delete the main context");f.A[a]=null;f.T.push(a)},183699:(a,b,c)=>{f.A[a].canvas.width=b;f.A[a].canvas.height=c},183774:(a,b,c,d,e)=>{f.A[a].fillStyle="rgba("+d+","+c+","+b+","+e/255+")"},183847:(a,b,c,d,e)=>{f.A[a].strokeStyle=
"rgba("+d+","+c+","+b+","+e/255+")"},183922:(a,b)=>{f.A[a].lineWidth=b},183958:(a,b)=>{f.A[a].font=b+"px Ubuntu"},184003:(a,b)=>{f.A[a].globalAlpha=b},184041:a=>{f.A[a].lineCap="round"},184080:a=>{f.A[a].lineJoin="round"},184120:a=>{f.A[a].textAlign="center"},184162:a=>{f.A[a].textBaseline="middle"},184207:a=>{f.A[a].beginPath()},184240:(a,b,c)=>{f.A[a].moveTo(b,c)},184276:(a,b,c)=>{f.A[a].lineTo(b,c)},184312:(a,b,c,d,e)=>{f.A[a].quadraticCurveTo(b,c,d,e)},184366:(a,b,c,d,e,g,h)=>{f.A[a].bezierCurveTo(b,
c,d,e,g,h)},184425:(a,b,c,d,e,g,h)=>{f.A[a].arc(b,c,d,e,g,!!h)},184476:(a,b,c,d,e,g)=>{f.A[a].ellipse(b,c,d,e,g,2*Math.PI,0)},184541:(a,b,c,d,e)=>{f.A[a].fillRect(b,c,d,e)},184587:(a,b,c,d,e)=>{f.A[a].strokeRect(b,c,d,e)},184635:(a,b,c,d,e)=>{f.A[a].rect(b,c,d,e)},184677:a=>{f.A[a].closePath()},184710:(a,b)=>{f.A[a].fill(b?"nonzero":"evenodd")},184764:a=>{f.A[a].stroke()},184794:a=>{f.A[a].clip()},184822:(a,b,c,d)=>{f.A[a].drawImage(f.A[b].canvas,c,d)},184885:(a,b,c,d,e)=>{const g=f.ta;g&&g.complete&&
0<g.naturalWidth&&f.A[a].drawImage(g,b,c,d,e)},185015:(a,b,c)=>{f.A[a].fillText(f.TextDecoder.decode(C.subarray(b,b+c)),0,0)},185104:(a,b,c)=>{f.A[a].strokeText(f.TextDecoder.decode(C.subarray(b,b+c)),0,0)},185195:(a,b,c)=>f.A[a].measureText(f.TextDecoder.decode(C.subarray(b,b+c)),0,0).width,185300:(a,b,c,d,e,g,h)=>{f.A[a].setTransform(b,c,e,g,d,h)},185358:a=>(a=window.localStorage[a?G(C,a):""])?W(a):0,185456:a=>{delete window.localStorage[a?G(C,a):""]},185506:(a,b)=>{window.localStorage[a?G(C,a):
""]=b?G(C,b):""},185568:()=>performance.now(),185598:(a,b,c)=>{a=a?G(C,a):"";const d=document.createElement("input");d.id=a;d.type=c?"password":"text";d.style.position="absolute";d.style["font-family"]="Ubuntu";d.style.display="none";d.style["border-width"]="0px";d.style.background="transparent";d.style.border="none";d.style.outline="none";d.style["padding-left"]="5px";d.maxLength=b.toString();d.setAttribute("spellcheck","false");document.body.appendChild(d)},186111:a=>{a=a?G(C,a):"";document.getElementById(a).style.display=
"block"},186220:a=>{a=a?G(C,a):"";document.getElementById(a).style.display="none"},186328:(a,b,c,d,e)=>{a=a?G(C,a):"";a=document.getElementById(a);a.style.left=(b-d/2)/devicePixelRatio+"px";a.style.top=(c-e/2)/devicePixelRatio+"px";a.style.width=d/devicePixelRatio-10+"px";a.style.height=e/devicePixelRatio+"px";a.style["font-size"]=e/devicePixelRatio*.66+"px"},186693:a=>{a=a?G(C,a):"";a=document.getElementById(a);return W(a.value)},186808:(a,b,c)=>{a=a?G(C,a):"";document.getElementById(a).value=(b?
G(C,b):"").slice(0,c)},186930:a=>{try{window.open(a?G(C,a):"")}catch(b){}},186985:()=>{window.addEventListener("keydown",a=>{!a.repeat&&nb(W(a.code),0)});window.addEventListener("keyup",a=>{!a.repeat&&nb(W(a.code),1)});window.addEventListener("mousedown",a=>{X(a.clientX*devicePixelRatio,a.clientY*devicePixelRatio,0,+!!a.button)});window.addEventListener("mousemove",a=>{X(a.clientX*devicePixelRatio,a.clientY*devicePixelRatio,1,+!!a.button)});window.addEventListener("mouseup",a=>{X(a.clientX*devicePixelRatio,
a.clientY*devicePixelRatio,2,+!!a.button)});window.addEventListener("touchstart",a=>{for(const b of a.changedTouches)Y(b.clientX*devicePixelRatio,b.clientY*devicePixelRatio,0,b.identifier)},{passive:!1});window.addEventListener("touchmove",a=>{for(const b of a.changedTouches)Y(b.clientX*devicePixelRatio,b.clientY*devicePixelRatio,1,b.identifier)},{passive:!1});window.addEventListener("touchend",a=>{for(const b of a.changedTouches)Y(b.clientX*devicePixelRatio,b.clientY*devicePixelRatio,2,b.identifier)},
{passive:!1});window.addEventListener("touchcancel",a=>{for(const b of a.changedTouches)Y(b.clientX*devicePixelRatio,b.clientY*devicePixelRatio,2,b.identifier)},{passive:!1});window.addEventListener("paste",a=>{try{const b=a.clipboardData.getData("text/plain");ob(W(b))}catch(b){}},{capture:!0});window.addEventListener("wheel",a=>{pb(a.deltaY)})},188639:()=>{function a(b){f.canvas.width=innerWidth*devicePixelRatio;f.canvas.height=innerHeight*devicePixelRatio;qb(b,innerWidth*devicePixelRatio,innerHeight*
devicePixelRatio);requestAnimationFrame(a)}requestAnimationFrame(a)},188910:()=>{f.canvas=document.getElementById("canvas");f.canvas.width=innerWidth*devicePixelRatio;f.canvas.height=innerHeight*devicePixelRatio;f.canvas.oncontextmenu=function(){return!1};window.onbeforeunload=function(){return"Are you sure?"};f.A=[];f.T=[];f.TextDecoder=new TextDecoder("utf8")},189289:()=>/iPhone|iPad|iPod|Android|BlackBerry/i.test(navigator.userAgent),189366:(a,b)=>{function c(){let e=f.socket=new WebSocket(d);
e.binaryType="arraybuffer";e.onopen=function(){Z(0,0,0)};e.onclose=function(g){Z(2,g.code,W(g.reason));setTimeout(c,1E3)};e.onmessage=function(g){C.set(new Uint8Array(g.data),a);Z(1,g.data.byteLength,0)}}let d=b?G(C,b):"";setTimeout(c,1E3)},189830:(a,b)=>{1==f.socket?.readyState&&f.socket.send(C.subarray(a,a+b))},189922:(a,b,c,d)=>{window.localStorage[f.TextDecoder.decode(C.subarray(a,a+b))]=f.TextDecoder.decode(C.subarray(c,c+d))},190056:(a,b,c,d)=>{a=window.localStorage[f.TextDecoder.decode(C.subarray(a,
a+b))];if(!a)return 0;a=a.slice(0,d);C.set((new TextEncoder).encode(a),c);return a.length}},rb,X,nb,Y,pb,ob,qb,Z,mb,sb,tb={b:(a,b,c,d)=>y(`Assertion failed: ${a?G(C,a):""}, at: `+[b?b?G(C,b):"":"unknown filename",c,d?d?G(C,d):"":"unknown function"]),c:(a,b,c)=>{a=new xa(a);B[a.S+16>>2]=0;B[a.S+4>>2]=b;B[a.S+8>>2]=c;za++;y()},i:()=>y(""),e:(a,b,c)=>Da(a,b,c),a:(a,b,c)=>Da(a,b,c),d:(a,b,c)=>Da(a,b,c),j:()=>Date.now(),h:()=>{y("OOM")},k:(a,b)=>{var c=0,d=0,e;for(e of Ga()){var g=b+c;B[a+d>>2]=g;c+=Aa(e,
C,g,Infinity)+1;d+=4}return 0},l:(a,b)=>{var c=Ga();B[a>>2]=c.length;a=0;for(var d of c)a+=Ha(d)+1;B[b>>2]=a;return 0},m:function(a){try{var b=R(a);if(null===b.fd)throw new H(8);b.X&&(b.X=null);try{b.C.close&&b.C.close(b)}catch(c){throw c;}finally{L[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof V||"ErrnoError"!==c.name)throw c;return c.N}},n:function(a,b,c,d){try{a:{var e=R(a);a=b;for(var g,h=b=0;h<c;h++){var r=B[a>>2],t=B[a+4>>2];a+=8;var m=e,A=r,u=t,v=g,ya=z;if(0>u||0>v)throw new H(28);
if(null===m.fd)throw new H(8);if(1===(m.flags&2097155))throw new H(8);if(16384===(m.node.mode&61440))throw new H(31);if(!m.C.read)throw new H(28);var N="undefined"!=typeof v;if(!N)v=m.position;else if(!m.seekable)throw new H(70);var O=m.C.read(m,ya,A,u,v);N||(m.position+=O);var x=O;if(0>x){var P=-1;break a}b+=x;if(x<t)break;"undefined"!=typeof g&&(g+=x)}P=b}B[d>>2]=P;return 0}catch(E){if("undefined"==typeof V||"ErrnoError"!==E.name)throw E;return E.N}},g:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<
b?NaN:Number(b);try{if(isNaN(b))return 22;var e=R(a);lb(e,b,c);pa[d>>3]=BigInt(e.position);e.X&&0===b&&0===c&&(e.X=null);return 0}catch(g){if("undefined"==typeof V||"ErrnoError"!==g.name)throw g;return g.N}},f:function(a,b,c,d){try{a:{var e=R(a);a=b;for(var g,h=b=0;h<c;h++){var r=B[a>>2],t=B[a+4>>2];a+=8;var m=e,A=r,u=t,v=g,ya=z;if(0>u||0>v)throw new H(28);if(null===m.fd)throw new H(8);if(0===(m.flags&2097155))throw new H(8);if(16384===(m.node.mode&61440))throw new H(31);if(!m.C.write)throw new H(28);
m.seekable&&m.flags&1024&&lb(m,0,2);var N="undefined"!=typeof v;if(!N)v=m.position;else if(!m.seekable)throw new H(70);var O=m.C.write(m,ya,A,u,v,void 0);N||(m.position+=O);var x=O;if(0>x){var P=-1;break a}b+=x;if(x<t)break;"undefined"!=typeof g&&(g+=x)}P=b}B[d>>2]=P;return 0}catch(E){if("undefined"==typeof V||"ErrnoError"!==E.name)throw E;return E.N}}};
function ub(){function a(){f.calledRun=!0;if(!ia){if(!f.noFSInit&&!bb){var b,c;bb=!0;b??=f.stdin;c??=f.stdout;d??=f.stderr;b?U("stdin",b):jb("/dev/tty","/dev/stdin");c?U("stdout",null,c):jb("/dev/tty","/dev/stdout");d?U("stderr",null,d):jb("/dev/tty1","/dev/stderr");kb("/dev/stdin",0);kb("/dev/stdout",1);kb("/dev/stderr",1)}vb.p();cb=!1;f.onRuntimeInitialized?.();if(!f.noInitialRun){var d=rb;try{var e=d(0,0);va||(f.onExit?.(e),ia=!0);da(e,new na(e))}catch(g){g instanceof na||"unwind"==g||da(1,g)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)e=f.postRun.shift(),sa.push(e);ra(sa)}}if(0<D)F=ub;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ua();ra(ta);0<D?F=ub:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}var vb;
(async function(){function a(c){c=vb=c.exports;rb=f._main=c.q;X=f._mouse_event=c.r;nb=f._key_event=c.s;Y=f._touch_event=c.t;pb=f._wheel_event=c.u;ob=f._clipboard_event=c.v;qb=f._loop=c.w;Z=f._on_message=c.x;mb=c.y;sb=c.o;c=sb.buffer;z=new Int8Array(c);new Int16Array(c);C=new Uint8Array(c);new Uint16Array(c);oa=new Int32Array(c);B=new Uint32Array(c);new Float32Array(c);qa=new Float64Array(c);pa=new BigInt64Array(c);new BigUint64Array(c);D--;f.monitorRunDependencies?.(D);0==D&&F&&(c=F,F=null,c());return vb}
D++;f.monitorRunDependencies?.(D);var b={a:tb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ja??=f.locateFile?f.locateFile("floir-client.wasm",l):l+"floir-client.wasm";return a((await ma(b)).instance)})();ub();
