var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,k=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,ca="./this.program",da=(a,b)=>{throw b;},ea=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ea=__filename:ba&&(ea=self.location.href);var l="",fa,q;
if(k){var fs=require("node:fs");l=__dirname+"/";q=a=>{a=t(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=t(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{l=(new URL(".",ea)).href}catch{}ba&&(q=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
fa=async a=>{if(t(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ha=console.log.bind(console),A=console.error.bind(console),G,ia=!1,t=a=>a.startsWith("file://");
function I(a){f.onAbort?.(a);a=`Aborted(${a})`;A(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ja;async function ka(a){if(!G)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==ja&&G)a=new Uint8Array(G);else if(q)a=q(a);else throw"both async and sync fetching of the wasm failed";return a}async function la(a,b){try{var c=await ka(a);return await WebAssembly.instantiate(c,b)}catch(d){A(`failed to asynchronously prepare wasm: ${d}`),I(d)}}
async function ma(a){var b=ja;if(!G&&!t(b)&&!k)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){A(`wasm streaming compile failed: ${d}`),A("falling back to ArrayBuffer instantiation")}return la(b,a)}class na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var oa,pa,J,qa,K,L,ra=a=>{for(;0<a.length;)a.shift()(f)},sa=[],ta=[],ua=()=>{var a=f.preRun.shift();ta.push(a)},M=0,N=null,va=!0,wa=globalThis.TextDecoder&&new TextDecoder,O=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&wa)return wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class xa{constructor(a){this.U=a-24}}
var ya=0,za=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;h++}}b[c]=0;return c-e},Aa=[],Ca=(a,b,c)=>{Aa.length=0;for(var d;d=L[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;
Aa.push(112==d?K[c>>2]:106==d?pa[c>>3]:105==d?oa[c>>2]:qa[c>>3]);c+=e?8:4}return Ba[a](...Aa)},Da={},Fa=()=>{if(!Ea){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Da)void 0===Da[b]?delete a[b]:a[b]=Da[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ea=c}return Ea},Ea,Ga=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=
d?(b+=4,++c):b+=3}return b},Ha=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ia=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ha(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ja=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+
b},Ka=()=>{if(k){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(crypto.getRandomValues(b),0)},La=a=>(La=Ka())(a),Ma=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ha(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Na=[],Oa=[];function Pa(a,b){Oa[a]={input:[],output:[],N:b};Qa(a,Ra)}
var Ra={open(a){var b=Oa[a.node.rdev];if(!b)throw new P(43);a.tty=b;a.seekable=!1},close(a){a.tty.N.fsync(a.tty)},fsync(a){a.tty.N.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.N.da)throw new P(60);for(var e=0,h=0;h<d;h++){try{var g=a.tty.N.da(a.tty)}catch(p){throw new P(29);}if(void 0===g&&0===e)throw new P(6);if(null===g||void 0===g)break;e++;b[c+h]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.N.aa)throw new P(60);try{for(var e=0;e<d;e++)a.tty.N.aa(a.tty,b[c+e])}catch(h){throw new P(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Sa={da(){a:{if(!Na.length){var a=null;if(k){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(Ga(a)+1);a=za(a,b,0,b.length);b.length=a;Na=b}a=Na.shift()}return a},aa(a,b){null===b||10===b?(ha(O(a.output)),a.output=
[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ha(O(a.output)),a.output=[])},Fa(){return{Ba:25856,Da:5,Aa:191,Ca:35387,za:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ga(){return 0},Ha(){return[24,80]}},Ta={aa(a,b){null===b||10===b?(A(O(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(A(O(a.output)),a.output=[])}},Q={I:null,K(){return Q.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(63);
Q.I||(Q.I={dir:{node:{L:Q.B.L,J:Q.B.J,lookup:Q.B.lookup,R:Q.B.R,rename:Q.B.rename,unlink:Q.B.unlink,rmdir:Q.B.rmdir,readdir:Q.B.readdir,symlink:Q.B.symlink},stream:{H:Q.C.H}},file:{node:{L:Q.B.L,J:Q.B.J},stream:{H:Q.C.H,read:Q.C.read,write:Q.C.write,ia:Q.C.ia,ka:Q.C.ka}},link:{node:{L:Q.B.L,J:Q.B.J,readlink:Q.B.readlink},stream:{}},ba:{node:{L:Q.B.L,J:Q.B.J},stream:Ua}});c=Va(a,b,c,d);16384===(c.mode&61440)?(c.B=Q.I.dir.node,c.C=Q.I.dir.stream,c.D={}):32768===(c.mode&61440)?(c.B=Q.I.file.node,c.C=
Q.I.file.stream,c.G=0,c.D=Q.ma??(Q.ma=new Uint8Array(0))):40960===(c.mode&61440)?(c.B=Q.I.link.node,c.C=Q.I.link.stream):8192===(c.mode&61440)&&(c.B=Q.I.ba.node,c.C=Q.I.ba.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.D[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},B:{L(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.G:40960===(a.mode&61440)?b.size=a.link.length:
b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},J(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.G!=b&&(c=a.D,a.D=new Uint8Array(b),a.D.set(c.subarray(0,Math.min(b,a.G))),a.G=b))},lookup(){Q.W||(Q.W=new P(44),Q.W.stack="<generic error, no stack>");throw Q.W;},R(a,b,c,d){return Q.createNode(a,b,c,d)},rename(a,b,c){try{var d=R(b,c)}catch(h){}if(d){if(16384===
(a.mode&61440))for(var e in d.D)throw new P(55);e=Wa(d.parent.id,d.name);if(S[e]===d)S[e]=d.M;else for(e=S[e];e;){if(e.M===d){e.M=d.M;break}e=e.M}}delete a.parent.D[a.name];b.D[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.D[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=R(a,b),d;for(d in c.D)throw new P(55);delete a.D[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.D)]},symlink(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;
return a},readlink(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},C:{read(a,b,c,d,e){if(e>=a.node.G)return 0;d=Math.min(a.node.G-e,d);b.set(a.node.D.subarray(e,e+d),c);return d},write(a,b,c,d,e,h){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(h)a.D=b.subarray(c,c+d),a.G=d;else if(0===a.G&&0===e)a.D=b.slice(c,c+d),a.G=d;else{h=e+d;var g=a.D.length;g>=h||(h=Math.max(h,g*(1048576>g?2:1.125)>>>0),g&&(h=Math.max(h,256)),g=a.D.subarray(0,a.G),a.D=new Uint8Array(h),a.D.set(g));a.D.set(b.subarray(c,
c+d),e);a.G=Math.max(a.G,e+d)}return d},H(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.G);if(0>b)throw new P(28);return b},ia(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.D;if(e&2||a.buffer!==J.buffer){d=!0;I();e=void 0;if(!e)throw new P(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);J.set(a,e)}}else d=!1,e=a.byteOffset;return{U:e,ya:d}},ka(a,b,c,d){Q.C.write(a,b,0,d,c,!1);return 0}}},Xa=(a,b)=>
{var c=0;a&&(c|=365);b&&(c|=146);return c},Ya=null,Za={},T=[],$a=1,S=null,ab=!1,bb=!0,P=class{name="ErrnoError";constructor(a){this.O=a}},cb=class{P={};node=null;get flags(){return this.P.flags}set flags(a){this.P.flags=a}get position(){return this.P.position}set position(a){this.P.position=a}},db=class{B={};C={};S=null;constructor(a,b,c,d){a||=this;this.parent=a;this.K=a.K;this.id=$a++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&
365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function U(a,b={}){if(!a)throw new P(44);b.Y??(b.Y=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(p=>!!p);for(var d=Ya,e="/",h=0;h<a.length;h++){var g=h===a.length-1;if(g&&b.parent)break;if("."!==a[h])if(".."===a[h])if(e=Ja(e),d===d.parent){a=e+"/"+a.slice(h+1).join("/");c--;continue a}else d=d.parent;else{e=Ia(e+"/"+a[h]);try{d=R(d,a[h])}catch(p){if(44===p?.O&&g&&b.wa)return{path:e};throw p;}!d.S||g&&!b.Y||(d=d.S.root);if(40960===(d.mode&61440)&&(!g||b.X)){if(!d.B.readlink)throw new P(52);
d=d.B.readlink(d);"/"===d.charAt(0)||(d=Ja(e)+"/"+d);a=d+"/"+a.slice(h+1).join("/");continue a}}}return{path:e,node:d}}throw new P(32);}function Wa(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function R(a,b){var c=16384===(a.mode&61440)?(c=eb(a,"x"))?c:a.B.lookup?0:2:54;if(c)throw new P(c);for(c=S[Wa(a.id,b)];c;c=c.M){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.B.lookup(a,b)}
function Va(a,b,c,d){a=new db(a,b,c,d);b=Wa(a.parent.id,a.name);a.M=S[b];return S[b]=a}function eb(a,b){return bb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function fb(a,b){if(16384!==(a.mode&61440))return 54;try{return R(a,b),20}catch(c){}return eb(a,"wx")}function V(a){a=T[a];if(!a)throw new P(8);return a}
function gb(a,b){var c=null?.C.J,d=c?null:a;c??=a.B.J;if(!c)throw new P(63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new P(22);throw e;}}var Ua={open(a){a.C=Za[a.node.rdev].C;a.C.open?.(a)},H(){throw new P(70);}};function Qa(a,b){Za[a]={C:b}}
function hb(a,b){var c="/"===b;if(c&&Ya)throw new P(10);if(!c&&b){var d=U(b,{Y:!1});b=d.path;d=d.node;if(d.S)throw new P(10);if(16384!==(d.mode&61440))throw new P(54);}b={type:a,Ja:{},ja:b,va:[]};a=a.K(b);a.K=b;b.root=a;c?Ya=a:d&&(d.S=b,d.K&&d.K.va.push(b))}function ib(a,b,c){var d=U(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new P(28);if("."===a||".."===a)throw new P(20);var e=fb(d,a);if(e)throw new P(e);if(!d.B.R)throw new P(63);return d.B.R(d,a,b,c)}
function W(a){return ib(a,16895,0)}function jb(a,b,c){"undefined"==typeof c&&(c=b,b=438);ib(a,b|8192,c)}function kb(a,b){if(!Ma(a))throw new P(44);var c=U(b,{parent:!0}).node;if(!c)throw new P(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=fb(c,b);if(d)throw new P(d);if(!c.B.symlink)throw new P(63);c.B.symlink(c,b,a)}
function lb(a,b){if(""===a)throw new P(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");var h=U(a,{X:!(b&131072),wa:!0});d=h.node;a=h.path}h=!1;if(b&64)if(d){if(b&128)throw new P(20);}else{if(e)throw new P(31);d=ib(a,c|511,0);h=!0}if(!d)throw new P(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new P(54);
if(!h&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=16384===(d.mode&61440)&&("r"!==e||b&576)?31:eb(d,e)):e=44,e))throw new P(e);if(b&512&&!h){e=d;e="string"==typeof e?U(e,{X:!0}).node:e;if(16384===(e.mode&61440))throw new P(31);if(32768!==(e.mode&61440))throw new P(28);if(a=eb(e,"w"))throw new P(a);gb(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.K.ja;var g=g?"/"!==e[e.length-1]?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:e.name;e=e.parent}b={node:d,
path:g,flags:b&-131713,seekable:!0,position:0,C:d.C,xa:[],error:!1};g=-1;b=Object.assign(new cb,b);if(-1==g)a:{for(g=0;4096>=g;g++)if(!T[g])break a;throw new P(33);}b.fd=g;T[g]=b;b.C.open&&b.C.open(b);h&&(c&=511,d="string"==typeof d?U(d,{X:!0}).node:d,gb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Ea:void 0}))}function mb(a,b,c){if(null===a.fd)throw new P(8);if(!a.seekable||!a.C.H)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.C.H(a,b,c);a.xa=[]}
function X(a,b,c){a=Ia("/dev/"+a);var d=Xa(!!b,!!c);X.ga??(X.ga=64);var e=X.ga++<<8|0;Qa(e,{open(h){h.seekable=!1},close(){c?.buffer?.length&&c(10)},read(h,g,p,n){for(var m=0,C=0;C<n;C++){try{var x=b()}catch(y){throw new P(29);}if(void 0===x&&0===m)throw new P(6);if(null===x||void 0===x)break;m++;g[p+C]=x}m&&(h.node.atime=Date.now());return m},write(h,g,p,n){for(var m=0;m<n;m++)try{c(g[p+m])}catch(C){throw new P(29);}n&&(h.node.mtime=h.node.ctime=Date.now());return m}});jb(a,d,e)}
var nb={},Y=a=>{var b=Ga(a)+1,c=ob(b);c&&za(a,L,c,b);return c};S=Array(4096);hb(Q,"/");W("/tmp");W("/home");W("/home/web_user");(function(){W("/dev");Qa(259,{read:()=>0,write:(d,e,h,g)=>g,H:()=>0});jb("/dev/null",259);Pa(1280,Sa);Pa(1536,Ta);jb("/dev/tty",1280);jb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(La(a),b=a.byteLength);return a[--b]};X("random",c);X("urandom",c);W("/dev/shm");W("/dev/shm/tmp")})();
(function(){W("/proc");var a=W("/proc/self");W("/proc/self/fd");hb({K(){var b=Va(a,"fd",16895,73);b.C={H:Q.C.H};b.B={lookup(c,d){c=+d;var e=V(c);c={parent:null,K:{ja:"fake"},B:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(T.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();f.noExitRuntime&&(va=f.noExitRuntime);f.print&&(ha=f.print);f.printErr&&(A=f.printErr);f.wasmBinary&&(G=f.wasmBinary);f.thisProgram&&(ca=f.thisProgram);
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();f.stringToNewUTF8=Y;
var Ba={1320260:a=>{f.A[a].save()},1320288:a=>{f.A[a].restore()},1320319:()=>{let a;a=0<f.V.length?f.V.pop():f.A.length;0===a?f.A[a]=document.getElementById("canvas").getContext("2d"):f.A[a]=(new OffscreenCanvas(1,1)).getContext("2d");return a},1320630:a=>{if(0==a)throw Error("Tried to delete the main context");f.A[a]=null;f.V.push(a)},1320755:(a,b,c)=>{f.A[a].canvas.width=b;f.A[a].canvas.height=c},1320830:(a,b,c,d,e)=>{f.A[a].fillStyle="rgba("+d+","+c+","+b+","+e/255+")"},1320903:(a,b,c,d,e)=>{f.A[a].strokeStyle=
"rgba("+d+","+c+","+b+","+e/255+")"},1320978:(a,b)=>{f.A[a].lineWidth=b},1321014:(a,b)=>{f.A[a].font=b+"px Ubuntu"},1321059:(a,b)=>{f.A[a].globalAlpha=b},1321097:a=>{f.A[a].lineCap="round"},1321136:a=>{f.A[a].lineJoin="round"},1321176:a=>{f.A[a].textAlign="center"},1321218:a=>{f.A[a].textAlign="left"},1321258:a=>{f.A[a].textAlign="right"},1321299:a=>{f.A[a].textBaseline="middle"},1321344:a=>{f.A[a].beginPath()},1321377:(a,b,c)=>{f.A[a].moveTo(b,c)},1321413:(a,b,c)=>{f.A[a].lineTo(b,c)},1321449:(a,
b,c,d,e)=>{f.A[a].quadraticCurveTo(b,c,d,e)},1321503:(a,b,c,d,e,h,g)=>{f.A[a].bezierCurveTo(b,c,d,e,h,g)},1321562:(a,b,c,d,e,h,g)=>{f.A[a].arc(b,c,d,e,h,!!g)},1321613:(a,b,c,d,e,h)=>{f.A[a].ellipse(b,c,d,e,h,2*Math.PI,0)},1321678:(a,b,c,d,e)=>{f.A[a].fillRect(b,c,d,e)},1321724:(a,b,c,d,e)=>{f.A[a].strokeRect(b,c,d,e)},1321772:(a,b,c,d,e)=>{f.A[a].rect(b,c,d,e)},1321814:a=>{f.A[a].closePath()},1321847:(a,b)=>{f.A[a].fill(b?"nonzero":"evenodd")},1321901:a=>{f.A[a].stroke()},1321931:a=>{f.A[a].clip()},
1321959:(a,b,c,d)=>{f.A[a].drawImage(f.A[b].canvas,c,d)},1322022:(a,b,c,d,e,h)=>{a=f.A[a];const g=f.ea;if(g&&g.complete&&0!==g.naturalWidth){d=Math.max(1,Math.round(d));if(!f.fa||f.na!==d){const p=document.createElement("canvas");p.width=p.height=d;const n=p.getContext("2d");n.imageSmoothingEnabled=!0;n.drawImage(g,0,0,d,d);f.fa=a.createPattern(p,"repeat");f.na=d}a.save();a.fillStyle=f.fa;a.translate(b,c);a.fillRect(-b,-c,e,h);a.restore()}else a.fillStyle="#1ea761",a.fillRect(0,0,e,h)},1322684:(a,
b,c)=>{f.A[a].fillText(f.TextDecoder.decode(L.subarray(b,b+c)),0,0)},1322773:(a,b,c)=>{f.A[a].strokeText(f.TextDecoder.decode(L.subarray(b,b+c)),0,0)},1322864:(a,b,c)=>f.A[a].measureText(f.TextDecoder.decode(L.subarray(b,b+c)),0,0).width,1322969:(a,b,c,d,e,h,g)=>{f.A[a].setTransform(b,c,e,h,d,g)},1323027:()=>{f.ha=!1;fetch("map-data.json").then(function(a){return a.json()}).then(function(a){const b={};var c=a.tiles;for(var d in c)b[d]=c[d].map(function(g){return{path:new Path2D(g.d),fill:g.fill,stroke:g.stroke,
la:g.sw,T:g.op}});c=a.layers;d=c.length;const e=[];for(var h=0;h<d;h++)e.push(new Map);h=a.placements;for(let g=0;g<h.length;g++){const p=h[g];e[p.l].set(50*p.r+p.c,p)}f.ua=b;f.qa=e;f.pa=c;f.ra=a.objects;f.Ia=d;f.oa=a.cell;f.ta=a.tileSize;f.ha=!0})},1323906:(a,b,c,d,e)=>{function h(u,F){const B=0!==(F&2147483648),H=0!==(F&536870912);0!==(F&1073741824)&&u.transform(1,0,0,-1,0,m);B&&u.transform(-1,0,0,1,m,0);H&&u.transform(0,1,1,0,0,0)}function g(u,F){n.save();h(n,F);for(const B of u)void 0!==B.T&&
1>B.T||(B.fill&&(n.fillStyle=B.fill,n.fill(B.path)),B.stroke&&(n.strokeStyle=B.stroke,n.lineWidth=B.la,n.lineJoin="round",n.stroke(B.path)));n.restore()}function p(u,F,B){u.save();h(u,B);for(const H of F)void 0===H.T||1<=H.T||(H.fill&&(u.fillStyle="#000",u.fill(H.path)),H.stroke&&(u.strokeStyle="#000",u.lineWidth=H.la,u.lineJoin="round",u.stroke(H.path)));u.restore()}if(f.ha){var n=f.A[a];a=f.oa;var m=f.ta,C=f.ua,x=f.qa,y=f.pa;f.$||(f.$=document.createElement("canvas"),f.sa=f.$.getContext("2d"));
var r=f.$,z=f.sa;if(r.width!==n.canvas.width||r.height!==n.canvas.height)r.width=n.canvas.width,r.height=n.canvas.height;for(let u=0;u<x.length;u++){const F=x[u];var w=y[u];if("bg"!==w&&"transitions"!==w){z.setTransform(1,0,0,1,0,0);z.clearRect(0,0,r.width,r.height);z.setTransform(n.getTransform());for(w=d;w<e;w++)for(var v=b;v<c;v++){var D=F.get(50*w+v);if(D){var E=C[D.gid];E&&(z.save(),z.translate(v*a-2,w*a-2),z.scale((a+4)/m,(a+4)/m),p(z,E,D.flip),z.restore())}}n.save();n.setTransform(1,0,0,1,
0,0);n.globalAlpha=.1;n.drawImage(r,0,0);n.restore()}for(w=d;w<e;w++)for(v=b;v<c;v++)if(D=F.get(50*w+v))if(E=C[D.gid])n.save(),n.translate(v*a-2,w*a-2),n.scale((a+4)/m,(a+4)/m),g(E,D.flip),n.restore()}x=f.ra;for(y=0;y<x.length;y++)r=x[y],!(z=C[r.gid])||r.x+r.w<b*a||r.x>c*a||r.y+r.h<d*a||r.y>e*a||(n.save(),n.translate(r.x,r.y),n.scale(r.w/m,r.h/m),g(z,r.flip),n.restore())}},1327311:a=>(a=window.localStorage[a?O(L,a):""])?Y(a):0,1327409:a=>{delete window.localStorage[a?O(L,a):""]},1327459:(a,b)=>{window.localStorage[a?
O(L,a):""]=b?O(L,b):""},1327521:()=>performance.now(),1327551:(a,b,c,d)=>{const e=a?O(L,a):"";a=document.createElement("input");a.id=e;a.type=c?"password":"text";a.style.position="absolute";a.style["font-family"]="Ubuntu";a.style.display="none";a.style["border-width"]="0px";a.style.background="transparent";a.style.border="none";a.style.outline="none";a.style["padding-left"]="5px";a.maxLength=b.toString();a.setAttribute("spellcheck","false");if(b=d?O(L,d):"")a.placeholder=b;document.body.appendChild(a)},
1328124:a=>{a=a?O(L,a):"";document.getElementById(a).style.display="block"},1328233:a=>{a=a?O(L,a):"";document.getElementById(a).style.display="none"},1328341:(a,b,c,d,e,h)=>{a=a?O(L,a):"";a=document.getElementById(a);const g=devicePixelRatio*(f.F||1);a.style.left=(b-d/2)/g+"px";a.style.top=(c-e/2)/g+"px";a.style.width=d/g-10+"px";a.style.height=e/g+"px";a.style["font-size"]=e/g*.66*h+"px"},1328698:a=>{a=a?O(L,a):"";a=document.getElementById(a);return Y(a.value)},1328813:(a,b,c)=>{a=a?O(L,a):"";document.getElementById(a).value=
(b?O(L,b):"").slice(0,c)},1328935:a=>{try{window.open(a?O(L,a):"")}catch(b){}},1328990:()=>{window.addEventListener("keydown",a=>{!a.repeat&&pb(Y(a.code),0)});window.addEventListener("keyup",a=>{!a.repeat&&pb(Y(a.code),1)});window.addEventListener("mousedown",a=>{qb(a.clientX*devicePixelRatio*(f.F||1),a.clientY*devicePixelRatio*(f.F||1),0,+!!a.button)});window.addEventListener("mousemove",a=>{qb(a.clientX*devicePixelRatio*(f.F||1),a.clientY*devicePixelRatio*(f.F||1),1,+!!a.button)});window.addEventListener("mouseup",
a=>{qb(a.clientX*devicePixelRatio*(f.F||1),a.clientY*devicePixelRatio*(f.F||1),2,+!!a.button)});window.addEventListener("touchstart",a=>{for(const b of a.changedTouches)Z(b.clientX*devicePixelRatio*(f.F||1),b.clientY*devicePixelRatio*(f.F||1),0,b.identifier)},{passive:!1});window.addEventListener("touchmove",a=>{for(const b of a.changedTouches)Z(b.clientX*devicePixelRatio*(f.F||1),b.clientY*devicePixelRatio*(f.F||1),1,b.identifier)},{passive:!1});window.addEventListener("touchend",a=>{for(const b of a.changedTouches)Z(b.clientX*
devicePixelRatio*(f.F||1),b.clientY*devicePixelRatio*(f.F||1),2,b.identifier)},{passive:!1});window.addEventListener("touchcancel",a=>{for(const b of a.changedTouches)Z(b.clientX*devicePixelRatio*(f.F||1),b.clientY*devicePixelRatio*(f.F||1),2,b.identifier)},{passive:!1});window.addEventListener("paste",a=>{try{const b=a.clipboardData.getData("text/plain");rb(Y(b))}catch(b){}},{capture:!0});window.addEventListener("wheel",a=>{sb(a.deltaY)})},1331008:()=>{function a(h){var g=tb();g!==c&&(c=g,e.style.display=
"flex",d=h+450);if(h-b>=(g?0:1E3/30-1)){b=h;f.F=g?1:.5;var p=devicePixelRatio*f.F;g=Math.max(1,Math.floor(innerWidth*p));p=Math.max(1,Math.floor(innerHeight*p));f.canvas.width=g;f.canvas.height=p;ub(h,g,p)}d&&h>=d&&(e.style.display="none",d=0);requestAnimationFrame(a)}let b=-1E9,c=tb(),d=0;const e=document.createElement("div");e.style.cssText="position:absolute;inset:0;background:#000;color:#fff;font:bold 48pt sans-serif;display:none;align-items:center;justify-content:center;z-index:10;";e.textContent=
"Loading";document.body.appendChild(e);requestAnimationFrame(a)},1332052:()=>{f.canvas=document.getElementById("canvas");f.canvas.width=innerWidth*devicePixelRatio;f.canvas.height=innerHeight*devicePixelRatio;f.canvas.oncontextmenu=function(){return!1};window.onbeforeunload=function(){return"Are you sure?"};f.A=[];f.V=[];f.TextDecoder=new TextDecoder("utf8");f.ea=new Image;f.ea.src="grass_bg.svg"},1332504:()=>/iPhone|iPad|iPod|Android|BlackBerry/i.test(navigator.userAgent),1332581:a=>{function b(){let d=
f.socket=new WebSocket(c);d.binaryType="arraybuffer";d.onopen=function(){vb(0,0,0)};d.onclose=function(e){vb(2,e.code,Y(e.reason));setTimeout(b,1E3)};d.onmessage=function(e){L.set(new Uint8Array(e.data),a);vb(1,e.data.byteLength,0)}}let c=("https:"===location.protocol?"wss://":"ws://")+location.host;setTimeout(b,1E3)},1333098:(a,b)=>{1==f.socket?.readyState&&f.socket.send(L.subarray(a,a+b))},1333190:(a,b,c,d)=>{window.localStorage[f.TextDecoder.decode(L.subarray(a,a+b))]=f.TextDecoder.decode(L.subarray(c,
c+d))},1333324:(a,b,c,d)=>{a=window.localStorage[f.TextDecoder.decode(L.subarray(a,a+b))];if(!a)return 0;a=a.slice(0,d);L.set((new TextEncoder).encode(a),c);return a.length}},wb,tb,qb,pb,Z,sb,rb,ub,vb,ob,xb,yb={b:(a,b,c,d)=>I(`Assertion failed: ${a?O(L,a):""}, at: `+[b?b?O(L,b):"":"unknown filename",c,d?d?O(L,d):"":"unknown function"]),c:(a,b,c)=>{a=new xa(a);K[a.U+16>>2]=0;K[a.U+4>>2]=b;K[a.U+8>>2]=c;ya++;I()},i:()=>I(""),e:(a,b,c)=>Ca(a,b,c),a:(a,b,c)=>Ca(a,b,c),d:(a,b,c)=>Ca(a,b,c),j:()=>Date.now(),
h:()=>{I("OOM")},k:(a,b)=>{var c=0,d=0,e;for(e of Fa()){var h=b+c;K[a+d>>2]=h;c+=za(e,L,h,Infinity)+1;d+=4}return 0},l:(a,b)=>{var c=Fa();K[a>>2]=c.length;a=0;for(var d of c)a+=Ga(d)+1;K[b>>2]=a;return 0},m:function(a){try{var b=V(a);if(null===b.fd)throw new P(8);b.Z&&(b.Z=null);try{b.C.close&&b.C.close(b)}catch(c){throw c;}finally{T[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof nb||"ErrnoError"!==c.name)throw c;return c.O}},n:function(a,b,c,d){try{a:{var e=V(a);a=b;for(var h,g=b=
0;g<c;g++){var p=K[a>>2],n=K[a+4>>2];a+=8;var m=e,C=p,x=n,y=h,r=J;if(0>x||0>y)throw new P(28);if(null===m.fd)throw new P(8);if(1===(m.flags&2097155))throw new P(8);if(16384===(m.node.mode&61440))throw new P(31);if(!m.C.read)throw new P(28);var z="undefined"!=typeof y;if(!z)y=m.position;else if(!m.seekable)throw new P(70);var w=m.C.read(m,r,C,x,y);z||(m.position+=w);var v=w;if(0>v){var D=-1;break a}b+=v;if(v<n)break;"undefined"!=typeof h&&(h+=v)}D=b}K[d>>2]=D;return 0}catch(E){if("undefined"==typeof nb||
"ErrnoError"!==E.name)throw E;return E.O}},g:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=V(a);mb(e,b,c);pa[d>>3]=BigInt(e.position);e.Z&&0===b&&0===c&&(e.Z=null);return 0}catch(h){if("undefined"==typeof nb||"ErrnoError"!==h.name)throw h;return h.O}},f:function(a,b,c,d){try{a:{var e=V(a);a=b;for(var h,g=b=0;g<c;g++){var p=K[a>>2],n=K[a+4>>2];a+=8;var m=e,C=p,x=n,y=h,r=J;if(0>x||0>y)throw new P(28);if(null===m.fd)throw new P(8);if(0===(m.flags&
2097155))throw new P(8);if(16384===(m.node.mode&61440))throw new P(31);if(!m.C.write)throw new P(28);m.seekable&&m.flags&1024&&mb(m,0,2);var z="undefined"!=typeof y;if(!z)y=m.position;else if(!m.seekable)throw new P(70);var w=m.C.write(m,r,C,x,y,void 0);z||(m.position+=w);var v=w;if(0>v){var D=-1;break a}b+=v;if(v<n)break;"undefined"!=typeof h&&(h+=v)}D=b}K[d>>2]=D;return 0}catch(E){if("undefined"==typeof nb||"ErrnoError"!==E.name)throw E;return E.O}}};
function zb(){function a(){f.calledRun=!0;if(!ia){if(!f.noFSInit&&!ab){var b,c;ab=!0;b??=f.stdin;c??=f.stdout;d??=f.stderr;b?X("stdin",b):kb("/dev/tty","/dev/stdin");c?X("stdout",null,c):kb("/dev/tty","/dev/stdout");d?X("stderr",null,d):kb("/dev/tty1","/dev/stderr");lb("/dev/stdin",0);lb("/dev/stdout",1);lb("/dev/stderr",1)}Ab.p();bb=!1;f.onRuntimeInitialized?.();if(!f.noInitialRun){var d=wb;try{var e=d(0,0);va||(f.onExit?.(e),ia=!0);da(e,new na(e))}catch(h){h instanceof na||"unwind"==h||da(1,h)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)e=f.postRun.shift(),sa.push(e);ra(sa)}}if(0<M)N=zb;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ua();ra(ta);0<M?N=zb:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}var Ab;
(async function(){function a(c){c=Ab=c.exports;wb=f._main=c.q;tb=f._get_high_quality=c.r;qb=f._mouse_event=c.s;pb=f._key_event=c.t;Z=f._touch_event=c.u;sb=f._wheel_event=c.v;rb=f._clipboard_event=c.w;ub=f._loop=c.x;vb=f._on_message=c.y;ob=c.z;xb=c.o;c=xb.buffer;J=new Int8Array(c);new Int16Array(c);L=new Uint8Array(c);new Uint16Array(c);oa=new Int32Array(c);K=new Uint32Array(c);new Float32Array(c);qa=new Float64Array(c);pa=new BigInt64Array(c);new BigUint64Array(c);M--;f.monitorRunDependencies?.(M);
0==M&&N&&(c=N,N=null,c());return Ab}M++;f.monitorRunDependencies?.(M);var b={a:yb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ja??=f.locateFile?f.locateFile("floir-client.wasm",l):l+"floir-client.wasm";return a((await ma(b)).instance)})();zb();
